# Site Variables
title: Brian Lockerbie
author: Brian Lockerbie
description: Brian Lockerbie's personal website
url: 'https://brianlockerbie.github.io/'
baseurl: 'https://brianlockerbie.github.io/'
# Permalink for blog posts
permalink: /blog/:year/:month/:title/

# Collections for portfolio
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/